all:
	gcc -Wall -c imageParser.c
	gcc -Wall -c matrix.c
	gcc -Wall -c mnistParser.c
	gcc -Wall -c testCase.c
	gcc -Wall -c network.c
	gcc -Wall -c convolutionalLayer.c
	gcc -Wall -c fullyConnectedLayer.c
	gcc -Wall -c sigmoid.c
	gcc -Wall main.c -lm
	rm *.o

